spring:
  application:
    name: dormung-springboot

  # Database
  datasource:
    url: "jdbc:mysql://localhost:3306/jeju_audio_guide?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul"
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  # Redis
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      timeout: 2000ms

# Server
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api
  shutdown: graceful

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    com.mycompany.goormthonserver: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"