apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend.yaml
  - ingress.yaml
  # environment 파일들 제거

configMapGenerator:
  - name: app-config
    literals:
      - DB_HOST=mysql-service
      - DB_PORT=3306
      - DB_NAME=dormung_db
      - JEJU_VISIT_API_URL=https://api.visitjeju.net
      - APP_ENV=production
      - LOG_LEVEL=INFO
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=k8s
      - JPA_DDL_AUTO=validate
      - JPA_SHOW_SQL=false
      - APP_LOG_LEVEL=INFO
      - DB_POOL_SIZE=10
      - DB_POOL_MIN=5
      - DB_CONNECTION_TIMEOUT=30000
      - TOMCAT_MAX_THREADS=200
      - TOMCAT_MIN_THREADS=10
      - API_TIMEOUT=30000
      - JWT_EXPIRATION=86400000
      - APP_NAME=dormung-backend
      - APP_VERSION=1.0.0
      - CONTEXT_PATH=/

# Secret 생성 (민감한 정보)
secretGenerator:
  - name: app-secret
    literals:
      - DB_USERNAME=appuser
      - DB_PASSWORD=apppassword
      - JEJU_VISIT_API_KEY=.
      - LLM_API_KEY=your-llm-api-key-here
      - NAVER_CLIENT_ID=your-naver-client-id
      - NAVER_CLIENT_SECRET=your-naver-client-secret
      - AWS_ACCESS_KEY_ID=your-aws-access-key
      - AWS_SECRET_ACCESS_KEY=your-aws-secret-key
      - JWT_SECRET=your-jwt-secret-key-here60